<?php

namespace Dan\Plugin\VentooniricoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

use Dan\UserBundle\Entity\User;

/**
 * DesireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesireRepository extends EntityRepository
{
    /**
     * Get accounts ordered by position
     *
     * @return \DateTime 
     */
    public function findByGameId($gameId) {
        $user = $this->user;
        $qb = $this->createQueryBuilder('d')
                ->where("d.gameId = :gameId")
                ->setParameter('gameId', $gameId);
        return $qb->getQuery()->getResult();
    }
    
    public function findByOwner(User $user) {
        $qb = $this->createQueryBuilder('d')
                ->andWhere("d.owner = :user")
                ->setParameter('user', $user)
            ;
        return $qb->getQuery()->getResult();
    }
}
