<?php

namespace Dan\Plugin\VentooniricoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function findAll()
    {
        $qb = $this->createQueryBuilder('g')
                ->orderBy('g.name','asc');
        return $qb->getQuery()->getResult();
    }
    
    public function findDesired()
    {
        $qb = $this->createQueryBuilder('g')
                ->join('g.desires', 'd')
                ->orderBy('d.createdAt','asc');
        return $qb->getQuery()->getResult();
    }
    
    public function getStaleGames($date = null)
    {
        if (!$date) {
            $date = new \DateTime('-1 day');
        }
        $qb = $this->createQueryBuilder('g')
                ->where('g.updatedAt < :date')
                ->setParameter('date', $date)
                ->orderBy('g.name','asc');
        
        return $qb->getQuery()->getResult();
    }
}
