<?php

namespace Dan\ShareBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShareTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareTokenRepository extends EntityRepository
{
}
