<?php

namespace Dan\UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserMetadataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMetadataRepository extends EntityRepository
{
}
